scrape_configs:
  - job_name: "opentelemetry-collector"
    scrape_interval: 5s
    static_configs:
      - targets: ["collector:8888"]

  - job_name: "applications"
    scrape_interval: 5s
    static_configs:
      - targets: ["collector:8889"]